<p><strong>Summary</strong></p>
<p>EnvoyAI<sup>&reg;</sup> <u>Developer Portal Account Summary</u> as of November 20th, 2018</p>
<p>&nbsp;</p>
<ul>
<li>EnvoyAI Inc. has established a Developer Portal to allow users to test algorithms relating to medical research and/or clinical practice.</li>
<li>After establishing an account, you will be able to invite other users to access algorithms in your account and receive invitations from other users to access algorithms in their account.</li>
<li>You will have either &ldquo;Developer&rdquo; rights or &ldquo;Viewer&rdquo; rights with respect to each algorithm to which you have access. Developer rights include the right to upload, view, use, edit and delete algorithms for nonproduction testing purposes. Viewer rights include solely the right to view and use the algorithm for nonproduction testing purposes.</li>
<li>In order to establish an account, you will need to agree in electronic form to the terms of a Developer Portal Account Agreement. (This summary is being provided for convenience only, and is qualified in its entirety by the Developer Portal Account Agreement.)</li>
</ul>
<p><strong>THIS ENVOYAI DEVELOPER PORTAL ACCOUNT AGREEMENT CONSTITUTES AN ENFORCEABLE LEGAL AGREEMENT BETWEEN YOU AND ENVOYAI. PLEASE READ THE TERMS CAREFULLY. BEFORE YOU MAY ACCESS OR USE AN ACCOUNT, YOU MUST AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS. IF YOU DO NOT AGREE TO THE TERMS, CONDITIONS AND RESTRICTIONS SET FORTH IN THIS AGREEMENT, ENVOYAI DOES NOT GRANT YOU THE RIGHT TO USE THE SERVICES. </strong></p>
<p><strong>Terms &amp; Conditions</strong></p>
<p><u>EnvoyAI Developer Portal Account Agreement</u></p>
<p>This Developer Portal Account Agreement (the &ldquo;Agreement&rdquo;) is a legally binding contract between you, as Developer, and EnvoyAI Inc. (&ldquo;EnvoyAI&rdquo;) and covers your account (&ldquo;Account&rdquo;) to access and use the EnvoyAI Developer Portal testing environment (&ldquo;Portal&rdquo;), a component of the EnvoyAI Platform Software Solution (&ldquo;Platform&rdquo;), along with EnvoyAI&rsquo;s Northstar<sup>&trade;</sup> AI Results Explorer (&ldquo;Northstar&rdquo;) in its then-current form. <u>By (i) clicking &ldquo;I Accept&rdquo; or a similar affirmation, <em>or </em>(ii) accessing or using your Account, you acknowledge and agree that your use of your Account, any products or services available to you in connection with the Portal, and any related documentation provided to you by EnvoyAI (&ldquo;Documentation&rdquo;), will be governed by this Agreement.</u> In this Agreement &ldquo;you&rdquo; and &ldquo;your&rdquo; refer to the individual that accepts this Agreement; if such individual is accessing the Developer Portal on behalf of a corporation or other legal entity (an &ldquo;Entity&rdquo;), you represent you have the authority to act on behalf of that Entity, and the Entity shall also be bound by the terms of this Agreement as if it were you. By creating an Account, you represent and warrant that you are of legal age to form a binding contract with EnvoyAI.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><strong>YOUR ACCOUNT</strong></p>
<p>To register an Account, you must provide your name, company or organization name and email address and create a password (&ldquo;Unique Identifiers&rdquo;). You must provide true, accurate, current and complete information about yourself as requested during the Account creation process. Your Unique Identifiers can be used only by you. You are solely responsible for the confidentiality of your Unique Identifiers, as well as for their use and misuse. You agree to take all reasonable precautions to prevent unauthorized access to or use of your Account and will notify EnvoyAI promptly of any unauthorized use or access. You will promptly inform EnvoyAI of any need to deactivate your Unique Identifiers. EnvoyAI reserves the right to delete your Unique Identifiers at any time and for any reason. EnvoyAI will not be liable for any loss or damage caused by any unauthorized use of your Unique Identifiers. You are solely responsible for all use (whether or not authorized) under your Account.</p>
<p><strong>USER DESIGNATION</strong></p>
<p>EnvoyAI has established the Portal and the opportunity for you and other people, entities and organizations (&ldquo;Users&rdquo;) to establish Accounts for the purpose of allowing Users to access one or more algorithms relating to medical research and/or clinical practice (each, an &ldquo;Algorithm&rdquo;) with the rights described herein. You may be associated with a single group (a &ldquo;Group&rdquo;) as part of the process of registering for an Account. A Group would typically (but is not required to) include employees and other personnel of a single Entity, or of the same department or unit within a single Entity. The Portal will enable you to invite other Users to join your Group, and to join a Group at the invitation of another User. You will have rights as either a &ldquo;Developer&rdquo; or &ldquo;Viewer&rdquo; with respect to each Algorithm made available to you through your Account: You will have Developer rights with respect to any Algorithm that is uploaded by you or another member of your Group, and you will have Viewer rights with respect to all other Algorithms made available to you. When you access an Algorithm within an Account, you will be electronically notified as to your status as a Viewer or Developer with respect to such Algorithm and such status shall determine the associated rights you have with respect to such Algorithm, as set forth herein.</p>
<p><strong>DEVELOPER AUTHORIZED USE</strong></p>
<p><u>If you are a Developer</u> with respect to an Algorithm, you have the right to (i) view and use such Algorithm within your Account for nonproduction testing purposes; (ii) edit and delete such Algorithm; and (iii) invite Users in Groups other than your Group to have &ldquo;Viewer&rdquo; status with respect to such Algorithm (collectively, the &ldquo;Developer Authorized Use&rdquo;). To the extent you are a Developer with respect to an Algorithm, EnvoyAI grants you, with respect to such Algorithm, a limited, non-exclusive, non-transferable license, without the right to grant sublicenses, to access and use your Account, the Portal, the Platform, Northstar in its then-current form, and any Documentation solely for the Developer Authorized Use.</p>
<p><strong>DEVELOPER REPRESENTATIONS AND LICENSES</strong></p>
<p><u>To the extent you are a Developer</u> with respect to an Algorithm, you hereby: (i) grant EnvoyAI a limited, non-exclusive, non-transferable license to provide other Users who are Viewers with respect to such Algorithm access and usage rights with respect to such Algorithm, limited to the Viewer Authorized Use (as defined below); (ii) grant each such Viewer a limited, non-exclusive, non-transferable license to access and view such Algorithm for the Viewer Authorized Use, subject in each case to the establishment by such Viewer of its own account to access and use the Portal; and (iii) represent and warrant that you have all rights necessary with respect to the applicable Algorithms associated with your Group to exercise the Developer Authorized Use and to grant the licenses described in this paragraph.</p>
<p><strong>VIEWER AUTHORIZED USE</strong></p>
<p><u>If you are a Viewer</u> with respect to an Algorithm, (i) you and other Users within your Group have the right to view and use such Algorithm for nonproduction testing purposes, without the right to edit or delete such Algorithm (the &ldquo;Viewer Authorized Use&rdquo;); and (ii) EnvoyAI grants you, with respect to such Algorithm, a limited, non-exclusive, non-transferable license, without the right to grant sublicenses, to then access and use the Account, the Portal, the Platform, Northstar in its then-current form, and the Documentation solely for the Viewer Authorized Use.</p>
<p><strong>RESTRICTIONS ON USE</strong></p>
<p><u>You shall not (and shall not permit any other User or third party to) make any use or disclosure of your Account, the Portal, the Platform, Northstar or the Documentation</u>, except as expressly permitted under this Agreement. Without limiting the foregoing, you shall not (and shall not permit any other User or third party to): (i) reverse engineer, decompile, disassemble, or otherwise attempt to discern the source code, object code, underlying structures, algorithms, ideas, know-how or any other information of or related to the Portal, Platform or Northstar; (ii) modify, translate, adapt or create derivative works based on the Portal, Platform, Northstar or the Documentation; (iii) make any copies of the Portal, Platform or Northstar software code or the Documentation; (iv) resell, distribute, or sublicense your Account, Platform, Northstar or the Documentation; (v) make your Account, the Portal, the Platform or Northstar available on a timesharing or &ldquo;service bureau&rdquo; basis, in any form, or otherwise allow any third party to use or access your Account, the Portal, the Platform, Northstar or the Documentation; (vi) remove or modify any proprietary marking or restrictive legends placed on or within the Portal, the Platform, Northstar or the Documentation; (vii) use the Account for any purpose not expressly permitted in this Agreement, or in violation of applicable law; (viii) introduce into your Account, the Portal, the Platform or Northstar any software, virus, worm, &ldquo;back door,&rdquo; trojan horse, or similar harmful code in any form; or (ix) provide to EnvoyAI or the Account any personally identifiable information or Protected Health Information (as such term is defined at 45 C.F.R. &sect; 164.501).</p>
<p>Additionally, you shall not (and shall not permit any other User or third party to): (i) impersonate, attempt to impersonate or misrepresent your identity or affiliation with EnvoyAI, another User or any other person or entity; (ii) engage in conduct that restricts or inhibits any other User&rsquo;s use or enjoyment of the Portal, or which, as determined by EnvoyAI, may harm EnvoyAI or other Users of the Portal or expose them to liability; (iii) use the Portal in any manner that could disable, overburden, damage or impair the Portal; (iv) use any robot, spider, automatic device, process or means, to access the Portal for any purpose, including monitoring or copying any material on the Portal; (v) use any manual process to monitor or copy any of the material on the Portal or for any other unauthorized purpose without EnvoyAI&rsquo;s prior written consent; (vi) use any device, software or routine that interferes with the proper working of the Portal; (vii) attempt to gain unauthorized access to, interfere with, damage or disrupt any parts of the Portal, the server on which the Portal is stored, or any server, computer, or database connected to the Portal; (viii) attack the Portal via a denial-of-service attack or distributed denial-of-service attack; and (ix) introduce material to the Portal that may infringe the intellectual property rights or other legal rights of another or that could give rise to any civil or criminal liability under applicable laws and regulations.</p>
<p><u>You shall not (and shall not permit any other User or third party to) access your Account from Internet Protocol addresses located outside of the United States and its territories except those listed here</u>: Afghanistan, Algeria, Australia, Austria, Belgium, Canada, Colombia, Costa Rica, Denmark, Djibouti, Dominica, Dominican Republic, Ecuador, Egypt, Eritrea, Europe, Finland, France, Germany, Greece, Guam, Guatemala, Vatican City State, Iceland, Iraq, Ireland, Israel, Italy, Japan, Latvia, Mexico, Netherlands, New Zealand, Nigeria, Norway, Peru, Portugal, Puerto Rico, Romania, Spain, Swaziland, Sweden, Switzerland, Syrian Arab Republic, Thailand, United Kingdom, United States Virgin Islands and British Virgin Islands.</p>
<p><u>If you are a Viewer</u> hereunder with respect to an Algorithm, the foregoing restrictions shall also apply to your use and access of such Algorithm.</p>
<p>EnvoyAI shall have the right, but not the obligation, to monitor your use of the Portal to ensure your compliance with these terms and conditions, including this Restrictions on Use section. If you violate the terms of this Restrictions on Use section, EnvoyAI reserves the right, in its sole discretion, to deny you access to the Account, or any portion thereof, without notice and to take appropriate legal action, as applicable.</p>
<p><strong>NO ANCILLARY SERVICES PROVIDED HEREWITH</strong></p>
<p>With the exception of the provision of instructions for use of the Developer Portal, EnvoyAI shall not provide you with any technical support services unless separately agreed to in writing. You shall be responsible for obtaining and maintaining any equipment and ancillary services needed to connect to, access or otherwise use your Account, including, without limitation, modems, hardware, servers, software, operating systems, networking, web servers and the like.</p>
<p><strong>TERM AND TERMINATION</strong></p>
<p>Your access to your Account shall be subject to a term of thirty (30) days with an automatic renewal period of thirty (30) days, unless terminated by you or EnvoyAI. EnvoyAI may terminate your Account, or any part of your Account, and this Agreement, without advance notice to you. If you would like to terminate your Account and this Agreement, you may email EnvoyAI at <a href="mailto:viswaath@envoyai.com">viswaath@envoyai.com</a>. Upon request, EnvoyAI will use reasonable commercial efforts to terminate your Account within seven (7) business days.</p>
<p><strong>UPDATES OF THIS AGREEMENT - NOTICE</strong></p>
<p>EnvoyAI may update and amend this Agreement at any time through a notice made available on the EnvoyAI Developer Portal. Your continued use of your Account after any such update or amendment with such notice shall constitute your agreement to such update or amendment.</p>
<p><strong>OWNERSHIP OF INTELLECTUAL PROPERTY</strong></p>
<p>With the exception of any Algorithms, as between EnvoyAI and you, EnvoyAI is and shall remain the sole and exclusive owner or authorized licensor of all right, title, and interest in and to the Portal, Documentation, the Platform and Northstar including all source code, object code, operating instructions, and all interfaces developed for or relating to the same, together with all modifications, enhancements, revisions, changes, copies, partial copies, translations, compilations, improvements, and derivative works thereof, and including all intellectual property rights therein. EnvoyAI claims no ownership rights to any Algorithm uploaded hereunder, and the applicable Developer, Group or other Entity that has developed and owns the Algorithm (the &ldquo;Algorithm Owner&rdquo;) shall remain the sole and exclusive owner of all right, title and interest in and to such Algorithm, and all intellectual property rights therein. EnvoyAI, and each Viewer with respect to an Algorithm, shall not: (i) reverse engineer, decompile, disassemble, or otherwise attempt to discern the source code, object code or underlying structures of such Algorithm; (ii) modify, translate, adapt or create derivative works based on such Algorithm; or (iii) make any copies of such Algorithm software code or any related documentation under this Agreement.</p>
<p>EnvoyAI, the EnvoyAI logo and any other EnvoyAI trademarks, graphics and logos used in connection with the Portal are trademarks or registered trademarks of EnvoyAI and may not be copied, imitated or used (in whole or in part) without EnvoyAI&rsquo;s prior written consent. All other trademarks, graphics and logos used in connection with Third Party Algorithms (&ldquo;Third Party Trademarks&rdquo;) are the property of their respective Algorithm Owners and the use of such Third Party Trademarks inures to the benefit of each owner. You are granted no right or license with respect to any of the aforesaid trademarks and any use of such trademarks.</p>
<p>THE USE OF YOUR ACCOUNT, OTHER THAN IN ACCORDANCE WITH THESE TERMS AND CONDITIONS, IS STRICTLY PROHIBITED AND MAY INFRINGE THE INTELLECTUAL PROPERTY RIGHTS OF ENVOYAI AND/OR THIRD PARTIES, WHICH MAY SUBJECT YOU TO CIVIL AND CRIMINAL PENALITIES, INCLUDING POSSIBLE MONETARY DAMAGES.</p>
<p><strong>CONFIDENTIALITY</strong></p>
<p><u>The Platform, Northstar and any non-public Documentation, as well as non-public information or material regarding EnvoyAI&rsquo;s customers, properties or data, and contracting forms and/or agreements themselves, are the confidential information of EnvoyAI and/or its licensor. You shall hold all such confidential information in strict confidence and shall not disclose any such confidential information to any other person or party</u> without the written consent of EnvoyAI. You shall take reasonable measures to maintain the confidentiality of the confidential information, which will in no event be less than the measures you use to maintain the confidentiality of your own confidential information, or information of a similar nature. You shall not use any confidential information for any purpose other than in connection with the Developer Authorized Use or Viewer Authorized Use, as the case may be. The Algorithms and any non-public Documentation related to the Algorithms are the confidential information of the applicable Algorithm Owner. EnvoyAI and any User with &ldquo;Viewer&rdquo; rights to any Algorithm shall hold such Algorithm as confidential information of the applicable Algorithm Owner in strict confidence, and shall not disclose any such confidential information to any other person or party without the written consent of the applicable Algorithm Owner. EnvoyAI and each Viewer shall take reasonable measures to maintain the confidentiality of the Algorithms, which will in no event be less than the measures EnvoyAI or the Viewer, as applicable, uses to maintain the confidentiality of its own information of a similar nature. EnvoyAI shall not use any confidential information for any purpose other than as expressly permitted under this Agreement.</p>
<p><strong>PRIVACY POLICY</strong></p>
<p>EnvoyAI is committed to protecting your privacy. Please refer to EnvoyAI&rsquo;s most recently published privacy policy located on the EnvoyAI website. This policy may be changed at any time, with or without written notice. Changes to such privacy policy will be posted on the EnvoyAI website.</p>
<p><strong>WARRANTY DISCLAIMER</strong></p>
<p><strong>THE ACCOUNT, PORTAL, PLATFORM, NORTHSTAR, DOCUMENTATION, AND ALL OTHER MATERIALS PROVIDED HEREUNDER ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE.&rdquo; ENVOYAI MAKES NO WARRANTY WITH RESPECT TO THE ACCOUNT, PORTAL, PLATFORM, NORTHSTAR, DOCUMENTATION, OR OTHERWISE IN CONNECTION WITH THIS AGREEMENT AND HEREBY DISCLAIMS ANY AND ALL EXPRESS, IMPLIED, OR STATUTORY WARRANTIES, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, AVAILABILITY, ACCURACY OR RELIABILITY OF RESULTS, ERROR-FREE OR UNINTERRUPTED OPERATION, CORRECTION OF ERRORS, AND ANY WARRANTIES ARISING FROM A COURSE OF DEALING, OR COURSE OF PERFORMANCE, OR USAGE OF TRADE.</strong> TO THE EXTENT THAT A PARTY MAY NOT AS A MATTER OF APPLICABLE LAW DISCLAIM ANY IMPLIED WARRANTY, THE SCOPE AND DURATION OF SUCH WARRANTY WILL BE THE MINIMUM PERMITTED UNDER SUCH LAW. EnvoyAI does not have any obligation to verify the identity of the persons accessing its services, nor does it have any obligation to monitor the use of its services by other users; therefore, <u>EnvoyAI disclaims all liability for identity theft or any other misuse of your identity or information by others</u>.</p>
<p><strong>NO ENDORSEMENT OF MEMBER CONTENT</strong></p>
<p>You acknowledge and agree that EnvoyAI does not endorse the content of any User or other third party, and is not responsible or liable for any such content, even though it could be unlawful, or otherwise objectionable or tortious, that it infringes or may infringe the intellectual property or other rights of another. <u>EnvoyAI is not responsible or liable to you or any third party for the content or accuracy of any materials provided by any third party, including but not limited to materials provided by Algorithm Owners</u>. You acknowledge that EnvoyAI does not pre-screen all content, but that EnvoyAI will have the right (but not the obligation) in its sole discretion to refuse, edit, move, or remove any content that is available via the service.</p>
<p><strong>INDEMNIFICATION</strong></p>
<p>You shall indemnify, and hold harmless EnvoyAI and its affiliates, parents and/or subsidiaries, and their respective officers, directors, agents and employees (collectively, the &ldquo;Indemnified Parties&rdquo;), from and against any third-party claims, actions, proceedings, and suits and all related liabilities, damages, settlements, penalties, fines, costs and expenses (including reasonable attorneys&rsquo; fees and litigation expenses) incurred by any Indemnified Party arising out of or relating to: (i) any breach or alleged breach by you of any warranty, representation or obligation contained in this Agreement, (ii) any contract or agreement between you and a third party, (iii) any infringement or alleged infringement by you of any intellectual property right of a third party, (iv) any alleged or actual violation by you of any applicable laws or governmental regulations, and/or (v) any use by you of any Algorithm, whether as a Developer or Viewer, including any results of such Algorithm or use of results thereof.</p>
<p><strong>LIMITATION OF LIABILITY</strong></p>
<p><strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, BE IT TORT, CONTRACT, OR OTHERWISE, SHALL ENVOYAI BE LIABLE TO YOU OR ANY OTHER PERSON UNDER THIS AGREEMENT FOR ANY MONEY DAMAGES, WHETHER DIRECT, INDIRECT, SPECIAL, INCIDENTAL, COVER, RELIANCE OR CONSEQUENTIAL DAMAGES, EVEN IF ENVOYAI HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES. IN THE EVENT THAT NOTWITHSTANDING THE FOREGOING, ENVOYAI IS FOUND LIABLE TO YOU FOR DAMAGES FROM ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE), ENVOYAI&rsquo;S LIABILITY TO YOU WILL BE LIMITED TO THE SUM OF $500. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT APPLY TO YOU.</strong></p>
<p><strong>FAIR ALLOCATION OF RISK</strong></p>
<p>THE DISCLAIMER OF REPRESENTATIONS, WARRANTIES AND CONDITIONS AND LIMITATION OF LIABILITY CONSTITUTE AN ESSENTIAL PART OF THE AGREEMENT AND REFLECT A FAIR ALLOCATION OF RISK BETWEEN THE PARTIES. YOU ACKNOWLEDGE AND AGREE THAT BUT FOR THE DISCLAIMER OF REPRESENTATIONS, WARRANTIES AND CONDITIONS AND LIMITATION OF LIABILITY, NEITHER YOU NOR ANY OF YOUR LICENSORS WOULD ENTER INTO (INCLUDING GRANTING THE RIGHTS GRANTED HEREIN) THE AGREEMENT.</p>
<p><strong>GOVERNING LAW</strong></p>
<p>This Agreement shall be governed by and construed in accordance with the laws of the State of North Carolina without regard for choice of law provisions thereof. The terms of the U.N. Convention on Contracts for the International Sale of Goods shall not apply to this Agreement. You hereby consent and agree to the exclusive jurisdiction of the state and federal courts located in or for Durham County, North Carolina, for all suits, actions or proceedings directly or indirectly arising out of or relating to this Agreement, and waive any and all objections to such courts, including but not limited to objections based on improper venue or inconvenient forum, and you hereby irrevocably submit to the jurisdiction of such courts in any suits, actions or proceedings arising out of or relating to this Agreement.</p>
<p><strong>SEVERABILITY</strong></p>
<p>If any portion or provision of this Agreement is found invalid or unenforceable by a court of competent jurisdiction, that portion or provision shall be amended as may be permitted in law to achieve as nearly as possible the same effect as the original portion or provision, and the remainder of this Agreement shall remain in full force and effect. Any provision of this Agreement which is unenforceable in any jurisdiction and cannot be &ldquo;blue-penciled&rdquo; by the court to achieve the same effect as described above shall be ineffective only as to that jurisdiction, and only to the extent of such unenforceability, without invalidating the remaining provisions hereof.</p>
<p><strong>COMPLETE UNDERSTANDING</strong></p>
<p>This Agreement constitutes the final and complete agreement between the parties regarding the subject matter hereof, and supersedes any prior or contemporaneous communications, representations, or agreements between the parties, whether oral or written.</p>
<p><strong>MISCELLANEOUS</strong></p>
<p>Neither party shall assign or otherwise transfer its rights or obligations under this Agreement without the prior, written consent of the other party; provided that this Agreement may be assigned by EnvoyAI without your consent (i) to an Affiliate of EnvoyAI (&ldquo;Affiliate&rdquo; defined for this purpose as an individual or entity that controls, is controlled by, or is under common control with such party), or (ii) in connection with a sale of EnvoyAI&rsquo;s business, whether structured as an asset sale, merger, stock sale or otherwise. Nonperformance of either party will be excused to the extent that performance is rendered impossible by strike, fire, flood, governmental acts, orders or restrictions, failure of suppliers, or any other reason where failure to perform is beyond the control and not caused by the negligence of the non-performing party. Any failure by EnvoyAI to exercise or enforce any legal right or remedy contained in this Agreement, or which EnvoyAI may have the benefit of under applicable law, shall not constitute a waiver of those rights. No waiver of any provision of this Agreement by EnvoyAI shall constitute a waiver of any other provision hereof or a continuing waiver unless expressly provided in a written instrument.</p>
<p>For Direct Questions or Notices, please contact EnvoyAI at <a href="mailto:viswaath@envoyai.com">viswaath@envoyai.com</a>.</p>
<p>&nbsp;</p>
